name: dio_proxy
description: a proxy for Dio . dio_proxy  interceptor can help us debug network traffic .
version: 1.0.10
homepage: https://github.com/csdntm/dio_proxy

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  dio: ">=2.1.9 <=3.1.0"

dev_dependencies:
  test: ^1.15.2
  pretty_dio_logger: ^1.1.1
  pedantic: ^1.9.0
  # effective_dart: ^1.0.0
